name: fuel_dashboard_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - requests
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - pip
  - pip:
      - streamlit
      - streamlit-autorefresh
      - google-api-python-client
      - google-auth
      - google-auth-httplib2
